# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Catching Tears in the Rain---Curating Idioms for Dependently-Typed Programming
author: Jan de Muijnck-Hughes

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: tears-in-the-rain.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jfdm/tears-in-the-rain/

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

exclude_patterns: [README.md]
